<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>ag</string>
   </array>
  <key>name</key>
  <string>Algo</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.Algo</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(let)</string>
          <key>name</key>
          <string>keyword.Algo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(import)</string>
          <key>name</key>
          <string>keyword.control.import.Algo</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(//)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.Algo</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.Algo</string>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.Algo</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.Algo</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.Algo</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(-?[1-9][0-9]*|0)</string>
          <key>name</key>
          <string>constant.numeric.Algo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(-?[1-9]*[0-9]\.[0-9]+)</string>
          <key>name</key>
          <string>constant.numeric.Algo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(true|false)</string>
          <key>name</key>
          <string>constant.other.Algo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((-?[1-9][0-9]*|0)[\x{0020}]*/[\x{0020}]*(-?[1-9][0-9]*|0))</string>
          <key>name</key>
          <string>constant.numeric.Algo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(if|else)</string>
          <key>name</key>
          <string>keyword.control.conditional.Algo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(foreach|for|while|try|catch|throw)</string>
          <key>name</key>
          <string>keyword.control.Algo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(up to| as | in | from | at | sf| to )</string>
          <key>name</key>
          <string>keyword.operator.word.Algo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(null|true|false)</string>
          <key>name</key>
          <string>constant.language.Algo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(let|break|continue|enum|library|object|return|print|disregard|external|add|remove)</string>
          <key>name</key>
          <string>keyword.Algo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\+\=|\-\=|\/\=|\*\=|\+\+|\-\-|\+|\-|\/|\*|\^)</string>
          <key>name</key>
          <string>keyword.operator.arithmetic.Algo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\||\&amp;|==)</string>
          <key>name</key>
          <string>keyword.operator.logical.Algo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\=)</string>
          <key>name</key>
          <string>keyword.operator.assignment.Algo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(([a-zA-Z_0-9]+\.[a-zA-Z_0-9]+)+)</string>
          <key>name</key>
          <string>variable.Algo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-zA-Z_0-9]+)</string>
          <key>name</key>
          <string>variable.Algo</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>([a-zA-Z_0-9]\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>none.Algo</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>none.Algo</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\\.)</string>
          <key>name</key>
          <string>constant.character.escape.Algo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.*?(?!\\.).)</string>
          <key>name</key>
          <string>string.Algo</string>
        </dict>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>none.Algo</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-zA-Z_0-9]+)</string>
          <key>name</key>
          <string>variable.parameter.Algo</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
