language: csharp
solution: Algo.sln
install:
  - nuget restore Algo.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release Algo.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./AlgoTests/bin/Release/AlgoTests.dll

deploy:
  provider: releases
  api_key: $gh_oauth
  file: "algo"
  skip_cleanup: true
  on:
    tags: true