name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to the Algo language repository! For information on documentation, please visit [the wiki.](https://github.com/c272/algo-lang/wiki) Otherwise, just make sure your issue isn't a duplicate. Have fun!'
        pr-message: 'Thank you for contributing your first pieces of code to the Algo language repository. Make sure you abide by the code formatting guidelines and PR structure before requesting!'
